name: herdsman
description: Manage Git hooks in a centralized way. Analog husky in JS
version: 1.0.0
repository: https://github.com/AlexHCJP/herdsman
homepage: https://github.com/AlexHCJP/herdsman
issue_tracker: https://github.com/AlexHCJP/herdsman/issues

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
